Rebrand of the README and UI (helper => initializr)
Azure/AKS-Construction pull request #355
Opened 2022-08-31 22:18 UTC by khowling

## PR Summary

Updated README to provide a Quick start guide that should be easy to follow.
Update the initialize UI, to make more streamlined

![image](https://user-images.githubusercontent.com/1034202/187795089-912bedb5-f011-4522-9685-ed81fc191841.png)

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] This PR is ready to merge and is not **Work in Progress**
- [ ] Link to a filed issue
- [ ] Screenshot of UI changes (if PR includes UI changes)

2022-09-01 20:37 UTC, khowling commented
@Gordonby , I cleaned up the Quick Start formatting now, so happy for it to be merged, but please can you check the rest of the README pls.  

I'd love to get this live.

@mosabami are you happy with the rename from helper -> initializr? if not. I can change it back, but still keep the new formatting and README

2022-09-02 10:12 UTC, Gordonby requested changes

2022-09-02 10:12 UTC, Gordonby commented on helper/src/configpresets/principals.json
> +        "title": "Principles driven",
You mean "Principal driven"

2022-09-02 10:12 UTC, Gordonby commented on README.md
> +The AKS Bicep Accelerator is part of the official [AKS Landing Zone Accelerator (Enterprise Scale)](https://github.com/Azure/AKS-Landing-Zone-Accelerator) architectural approach. To read more about t
Aren't we dropping Bicep Accelerator?

2022-09-02 12:04 UTC, Gordonby commented
> @Gordonby , I cleaned up the Quick Start formatting now, so happy for it to be merged, but please can you check the rest of the README pls.
> 
> I'd love to get this live.
> 
> @mosabami are you happy with the rename from helper -> initializr? if not. I can change it back, but still keep the new formatting and README

We've pulled the rename to initializr for the time being @mosabami.

2022-09-02 12:09 UTC, Gordonby commented
@khowling - we need to also PR this repo to update from Bicep Accelerator.
https://github.com/Azure/AKS-Landing-Zone-Accelerator#bicep-aks-accelerator

2022-09-02 12:23 UTC, Gordonby submitted a review, later dismissed
LGTM

2022-09-02 12:31 UTC, Gordonby approved these changes
LGTM

2022-09-02 12:31 UTC, merged