add telemetry, minor fixes to GUI
Azure/AKS-Construction pull request #431
Opened 2022-10-18 00:08 UTC by mosabami

## PR Summary

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] This PR is ready to merge and is not **Work in Progress**
- [ ] Link to a filed issue
- [ ] Screenshot of UI changes (if PR includes UI changes)

2022-10-18 06:47 UTC, Gordonby commented
Which code prettifier did you use on main.bicep? @mosabami

2022-10-18 09:45 UTC, Gordonby requested changes

2022-10-18 09:45 UTC, Gordonby commented on bicep/main.bicep
> +  scope: tenant()
I think i've just answered my own question @mosabami 

Here is one of the errors from our CI from introducing your change. The deploying user needs significant elevation in their RBAC.
> ERROR: ***"error":***"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'Authorization failed for template resource '3c1e2fc6-1c4b-44f9-8694-25d00ae30a3a-eastus' of type 'Microsoft.Resources/deployments'. The client 'b5a69ed4-1f7e-4855-bbcc-b3cf2dc1b8dc' with object id 'b5a69ed4-1f7e-4855-bbcc-b3cf2dc1b8dc' does not have permission to perform action 'Microsoft.Resources/deployments/write' at scope '/providers/Microsoft.Resources/deployments/3c1e2fc6-1c4b-44f9-8694-25d00ae30a3a-eastus'

2022-10-18 09:59 UTC, Gordonby commented on bicep/main.bicep
> +  scope: tenant()
If i look at how [CARML track deployments](https://github.com/Azure/ResourceModules/blob/main/modules/Microsoft.ContainerRegistry/registries/replications/deploy.bicep#L26) then it doesn't appear we need to change the scope.

2022-10-18 15:26 UTC, mosabami commented on bicep/main.bicep
> +  scope: tenant()
ok @Gordonby  i changed the scope to aks

2022-10-19 07:34 UTC, Gordonby approved these changes
lgtm

2022-10-19 08:08 UTC, merged